const employeeData = [
    { id: '001', name: 'Hassan Hashmi', designation: 'Team Lead', teamName: 'WordPress', shiftTime: 'PKT', workingFrom: 'Office', checkInTime: '09:00 AM', checkOutTime: '06:00 PM', managerName: 'Muhammad Kassem', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/Hassan-Hashmi.jpg' },
    { id: '002', name: 'Aleksandar Mitic', designation: 'Fullstack Developer', teamName: 'WordPress', shiftTime: 'EST', workingFrom: 'Home Base', checkInTime: '08:00 AM', checkOutTime: '05:00 PM', managerName: 'Muhammad Kassem', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/team/amitic.png' },
    { id: '003', name: 'Sajjad Kahn', designation: 'FrontEnd Developer', teamName: 'WordPress', shiftTime: 'PKT', workingFrom: 'Office', checkInTime: '10:00 AM', checkOutTime: '07:00 PM', managerName: 'Muhammad Kassem', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/Sajjad%20Ali.jpg' },
    { id: '004', name: 'Usman Akhtar', designation: 'Team Lead', teamName: 'WordPress', shiftTime: 'EST', workingFrom: 'Home Base', checkInTime: '11:00 AM', checkOutTime: '08:00 PM', managerName: 'Muhammad Kassem', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/team/Usman-Akhtar.jpeg' },
    { id: '005', name: 'Asad Ur Rehman', designation: 'FrontEnd Developer', teamName: 'WordPress', shiftTime: 'PKT', workingFrom: 'Office', checkInTime: '12:00 PM', checkOutTime: '09:00 PM', managerName: 'Muhammad Kassem', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/asad%20ur%20rehman.jpg' },
    { id: '006', name: 'Hassan Durrani', designation: 'FrontEnd Developer', teamName: 'WordPress', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '01:00 PM', checkOutTime: '10:00 PM', managerName: 'Muhammad Kassem', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://www.computan.com/hubfs/durrani-pic.jpg' },
    { id: '007', name: 'John Smith', designation: 'Backend Developer', teamName: 'Hubspot Development', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '08:00 AM', checkOutTime: '05:00 PM', managerName: 'John Doe', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '008', name: 'Alice Johnson', designation: 'QA Engineer', teamName: 'Shopify/Ecommerce', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '09:00 AM', checkOutTime: '06:00 PM', managerName: 'Jane Smith', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '009', name: 'Michael Brown', designation: 'Devops & Security Engineer', teamName: 'Devops & Security', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '10:00 AM', checkOutTime: '07:00 PM', managerName: 'Fatima Noor', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0010', name: 'Emily Davis', designation: 'Frontend Developer', teamName: '.Net/Azure Team', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '11:00 AM', checkOutTime: '08:00 PM', managerName: 'Ali Ahmad', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0011', name: 'Daniel Wilson', designation: 'Fullstack Developer', teamName: 'Hubspot Development', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '12:00 PM', checkOutTime: '09:00 PM', managerName: 'John Doe', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0012', name: 'Sophia Moore', designation: 'Project Manager', teamName: 'Shopify/Ecommerce', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '01:00 PM', checkOutTime: '10:00 PM', managerName: 'Jane Smith', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0013', name: 'James Taylor', designation: 'UI/UX Designer', teamName: 'Devops & Security', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '02:00 PM', checkOutTime: '11:00 PM', managerName: 'Fatima Noor', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0014', name: 'Olivia Anderson', designation: 'Marketing Specialist', teamName: '.Net/Azure Team', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '03:00 PM', checkOutTime: '12:00 AM', managerName: 'Ali Ahmad', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0015', name: 'David Martinez', designation: 'SEO Specialist', teamName: 'Hubspot Development', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '04:00 PM', checkOutTime: '01:00 AM', managerName: 'John Doe', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0016', name: 'Isabella Harris', designation: 'Content Writer', teamName: 'Shopify/Ecommerce', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '05:00 PM', checkOutTime: '02:00 AM', managerName: 'Jane Smith', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0017', name: 'Joseph Clark', designation: 'Database Administrator', teamName: 'Devops & Security', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '06:00 PM', checkOutTime: '03:00 AM', managerName: 'Fatima Noor', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0018', name: 'Emma Lewis', designation: 'Data Analyst', teamName: '.Net/Azure Team', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '07:00 PM', checkOutTime: '04:00 AM', managerName: 'Ali Ahmad', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0019', name: 'Christopher Allen', designation: 'Network Engineer', teamName: 'Hubspot Development', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '08:00 PM', checkOutTime: '05:00 AM', managerName: 'John Doe', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0020', name: 'Charlotte King', designation: 'System Administrator', teamName: 'Shopify/Ecommerce', shiftTime: 'PKT', workingFrom: 'Home Base', checkInTime: '09:00 PM', checkOutTime: '06:00 AM', managerName: 'Jane Smith', calendarType: 'PK, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
    { id: '0021', name: 'Andrew Scott', designation: 'Backend Developer', teamName: 'Devops & Security', shiftTime: 'EST', workingFrom: 'Office', checkInTime: '10:00 PM', checkOutTime: '07:00 AM', managerName: 'Fatima Noor', calendarType: 'USA, Holiday Calendar', profilePhoto: 'https://timesheet.computan.com/computanLogo.png' },
  
  ];

  export default employeeData;